#!/usr/bin/python

from __future__ import division

import bls, ktransit, math, pylab, os, csv, untrendy, PyAstronomy

import numpy as np

from scipy.stats import gamma

from astropy.io import fits

import matplotlib.pyplot as plt

from pylab import xlabel, ylabel, title, plot, show, ylim, xlim

from astropy.stats import sigma_clip

from ktransit import FitTransit

from scipy import signal

from numpy import mean, sqrt, square, arange

from PyAstronomy import pyasl


tested_rprs = []
tested_period = []
recovered_rprs = []
recovered_period = []
recoveredarr = []

flux = []
merged_flux = []
time = []
campaign_no = []
targetname = []

tmod = []
mergedfluxDetrend = []
SDE = []

BLSper = []
RMSarr = []

z = [0, 0, 0, 0]

z[0] = -3.22185
z[1] = 1.02655
z[2] = 1.6613
z[3] = .225603

p = np.poly1d(z)


fig, ax = plt.subplots(1, 1, figsize=[15,10])
ax.set_xlabel('$\mathregular{R_p}$/$\mathregular{R_s}$', fontsize=14)
ax.set_xlim(0, 0.4)
ax.set_ylim(0, 26)

ax.set_ylabel('Orbital Period (days)', fontsize=14)
ax.set_title('EPIC 229227260')
ax.hold(True)



filecount = 1 #sum(1 for line in open('all_txt_files.txt'))

for i in range(100):
    print(i)
